[build]
  command = "npm run generate-json && npm run build"
  publish = "."  # Replace with your actual publish folder if different

[context.production]
  [context.production.environment]
    NODE_VERSION = "18" # Specify Node.js version if required
