backend:
  name: git-gateway
  branch: main
# local_backend: true  # Uncomment if you want to work locally

media_folder: "assets/img" # Folder where images are stored
public_folder: "/img" # URL to access images

identity_widget: true

media_library:
  name: uploadcare
  config:
    publicKey: "b4b6021208a7b8428d49"
    multiple: true
    previewStep: false

settings:
  autoFilename: true

collections:
  - name: "employee-newsletter"
    label: "Employee Newsletters"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "PDF File", name: "file", widget: "file", media_library: "uploadcare", required: false }
